workflows:
  build-ios-archive:
    name: Build iOS archive (export unsigned IPA)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: "15.2"
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "bolivision-ios.xcworkspace"
        XCODE_SCHEME: "bolivisionairtv"
    scripts:
      - name: Clean Pods
        script: |
          rm -rf Pods Podfile.lock
          pod deintegrate
          xcodebuild clean -project bolivision-ios.xcodeproj -scheme bolivisionairtv || true
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
      - name: Install pods
        script: |
          pod install --repo-update
      - name: Force iOS 13 deployment target
        script: |
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g' bolivision-ios.xcodeproj/project.pbxproj
          find Pods -name "project.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g' {} +
      - name: Fix duplicate Info.plist issue
        script: |
          echo "🛠  Removing duplicate Info.plist from Copy Bundle Resources..."
          sed -i.bak '/Info.plist in Resources/d' bolivision-ios.xcodeproj/project.pbxproj || true
      - name: Create shared scheme if missing
        script: |
          set -e
          cd $CM_BUILD_DIR
          xcodebuild -list -project bolivision-ios.xcodeproj
          if [ ! -f "bolivision-ios.xcodeproj/xcshareddata/xcschemes/bolivisionairtv.xcscheme" ]; then
            echo "⚡ No scheme found, you need to add bolivisionairtv.xcscheme to your repo."
            exit 1
          fi
      - name: Prepare xcodebuild logs
        script: |
          mkdir -p /tmp/xcodebuild_logs
      - name: Build and archive (without Firebase)
        script: |
          set -o pipefail
          # Build y archive sin firmar ni usar Firebase
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/${XCODE_SCHEME}.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO
      - name: Package unsigned IPA
        script: |
          mkdir -p $CM_BUILD_DIR/build/ipa
          cd $CM_BUILD_DIR/build/${XCODE_SCHEME}.xcarchive/Products/Applications
          mkdir Payload
          cp -r bolivisionairtv.app Payload/
          zip -r9 $CM_BUILD_DIR/build/ipa/bolivisionairtv-unsigned.ipa Payload
    artifacts:
      - $CM_BUILD_DIR/build/ipa/*.ipa
  build-ios-preview:
    name: Build iOS App for Preview
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: "15.2"
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "bolivision-ios.xcworkspace"
        XCODE_SCHEME: "bolivisionairtv"
    scripts:
      - name: Clean Pods
        script: |
          rm -rf Pods Podfile.lock
          pod deintegrate
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
      - name: Install pods
        script: |
          pod install --repo-update
      - name: Build for Simulator
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath build
          # Copiar el .app al directorio de artifacts
          mkdir -p $CM_BUILD_DIR/build/app
          cp -r build/Build/Products/Debug-iphonesimulator/bolivisionairtv.app $CM_BUILD_DIR/build/app/
    artifacts:
      - $CM_BUILD_DIR/build/app/*.app
