workflows:
  build-ios-archive:
    name: Build iOS archive (export unsigned IPA)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: "15.2"
      cocoapods: default
      vars:
        XCODE_PROJECT: "bolivision-ios.xcodeproj"
        XCODE_SCHEME: "bolivisionairtv"
        EXPORT_OPTIONS_PLIST: "exportOptions.plist"
      groups:
        - firebase_credentials
    scripts:
      - name: Create shared scheme if missing
        script: |
          set -e
          cd $CM_BUILD_DIR
          xcodebuild -list -workspace bolivision-ios.xcworkspace
          if [ ! -f "bolivision-ios.xcodeproj/xcshareddata/xcschemes/bolivisionairtv.xcscheme" ]; then
            echo "⚡ No scheme found, creating one..."
            xcodegen || true
          fi
      - name: Prepare xcodebuild logs
        script: |
          mkdir -p /tmp/xcodebuild_logs
      - name: Build and archive
        script: |
          set -o pipefail
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Release -archivePath $CM_BUILD_DIR/build/${XCODE_SCHEME}.xcarchive archive | tee /tmp/xcodebuild_logs/build.log
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/${XCODE_SCHEME}.xcarchive -exportOptionsPlist $EXPORT_OPTIONS_PLIST -exportPath $CM_BUILD_DIR/build/ipa | tee /tmp/xcodebuild_logs/export.log || true
    artifacts:
      - $CM_BUILD_DIR/build/ipa/*.ipa
