workflows:
  build-ios-archive:
    name: Build iOS archive (export unsigned IPA)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: "15.2"
      cocoapods: default
      vars:
        XCODE_PROJECT: "bolivision-ios.xcodeproj"
        XCODE_SCHEME: "bolivisionairtv"
        EXPORT_OPTIONS_PLIST: "exportOptions.plist"
    scripts:
      - name: Fix duplicate Info.plist issue
        script: |
          echo "🛠  Removing duplicate Info.plist from Copy Bundle Resources..."
          sed -i.bak '/Info.plist in Resources/d' bolivision-ios.xcodeproj/project.pbxproj || true
      - name: Create shared scheme if missing
        script: |
          set -e
          cd $CM_BUILD_DIR
          xcodebuild -list -project bolivision-ios.xcodeproj
          if [ ! -f "bolivision-ios.xcodeproj/xcshareddata/xcschemes/bolivisionairtv.xcscheme" ]; then
            echo "⚡ No scheme found, you need to add bolivisionairtv.xcscheme to your repo."
            exit 1
          fi
      - name: Prepare xcodebuild logs
        script: |
          mkdir -p /tmp/xcodebuild_logs
      - name: Build and archive
        script: |
          set -o pipefail
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -configuration Release -archivePath $CM_BUILD_DIR/build/${XCODE_SCHEME}.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_ALLOWED=NO | tee /tmp/xcodebuild_logs/build.log
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/${XCODE_SCHEME}.xcarchive -exportOptionsPlist $EXPORT_OPTIONS_PLIST -exportPath $CM_BUILD_DIR/build/ipa | tee /tmp/xcodebuild_logs/export.log || true
    artifacts:
      - $CM_BUILD_DIR/build/ipa/*.ipa
