
workflows:
  build-ios-archive:
    name: Build iOS archive (export unsigned IPA)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: "15.2"
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "bolivision-ios.xcworkspace"
        XCODE_SCHEME: "bolivisionairtv"
        EXPORT_OPTIONS_PLIST: "exportOptions.plist"
      groups:
        - firebase_credentials
    scripts:
      - name: Pre-build - restore Firebase plist from secret (optional)
        script: |
          if [ ! -z "$IOS_FIREBASE_BASE64" ]; then
            echo "Restoring GoogleService-Info.plist from IOS_FIREBASE_BASE64..."
            mkdir -p ios/Bolivision
            echo "$IOS_FIREBASE_BASE64" | base64 --decode > ios/Bolivision/GoogleService-Info.plist
          else
            echo "No IOS_FIREBASE_BASE64 variable found; ensure GoogleService-Info.plist is in repo or uploaded as secret."
          fi
      - name: Prepare xcodebuild logs
        script: |
          mkdir -p /tmp/xcodebuild_logs
      - name: Install CocoaPods dependencies
        script: |
          pod install --repo-update || true
      - name: Build and archive
        script: |
          set -o pipefail
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Release -archivePath $CM_BUILD_DIR/build/${XCODE_SCHEME}.xcarchive archive | tee /tmp/xcodebuild_logs/build.log
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/${XCODE_SCHEME}.xcarchive -exportOptionsPlist $EXPORT_OPTIONS_PLIST -exportPath $CM_BUILD_DIR/build/ipa | tee /tmp/xcodebuild_logs/export.log || true
    artifacts:
      - $CM_BUILD_DIR/build/ipa/*.ipa
    triggers:
      - push
      - pull_request
